### ISSUE TITLE
Code review before merges

### ISSUE THREAD

**Issue by AdamSlodowy** [robashton/crowdsourcedhomepage#118]
Hello!

While I appreciate the sense of humour, after the initial smile my thought was: is actually anyone reviewing the code before the merges? If not you may well be fostering a nest for malicious stuff 👎

**Comment by robashton** [comment]
Nobody was reviewing it no, but only one person abused it and it was quickly rectified.

Merges are no longer automatic, because I took the server down that did the merges - so it's a moot point now anyway :)
