### ISSUE TITLE
Get your arse back on twitter

### ISSUE THREAD

**Issue by ChrisMcKee** [robashton/crowdsourcedhomepage#82]
Regards the 'non-existent' .net Community :smile_cat:

**Comment by maartenba** [comment]
+1

**Comment by robashton** [comment]
Nope, it was a long time coming. I'm disconnecting most things (I stopped saying yes to conference invites a few months ago, e-mail a few weeks ago, blog comments a week ago, "social media" this week, change of phone number in another few weeks).

I'll still be blogging tho, have no fear my reign of drivel will continue.
